#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server:
#
#Accepts 4 parameters
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
