#!/usr/bin/env bash
# Display "To infinity and beyond"indefinitely
# sleep 2 in between each iteration
# Displays "I am invincible!!!" when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
