#!/usr/bin/env bash
# Bash script that displays content of file '/etc/passwd.'
# Only display username, user id, user home directory

while read -r passwd;do
	echo "$passwd" | cut -d ':' -f1, 3, 6
done
