#!/usr/bin/env bash
# Bash script that loops 1 to 10 and display "bad luck" for 4th loop iteration, "good luck" for 8th loop iteration, "Best School" for other iterations.

count = 0
while [$count -lt 10]
do
	if [$count -eq 3]
	then
		echo "bad luck"
	elif [$count -eq 7]
	then
		echo "good luck'
	else
		echo "Best School"
	fi
	((count++))
done
