#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
#	displays 4 then "bad luck from China" for 4th iteration
#	displays 9 then "bad luck from Japan" for 9th iteration
#	displays 17 then "bad luck from Italy" for 17th iteration

count = 1
while [$count -le 20]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((count++))
done
