#!/usr/bin/bash

echo -e "Installing UFW\n"

sudo apt-get install -y ufw
echo -e "configuring UFW...\n"
sudo ufw disable
sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

echo -e "Process Completed.\n"
